Layout/LineLength:
  Max: 100
  Exclude:
    - 'db/**/*'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/environments'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'db/**/*.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/**/*'
    - 'bin/**/*'
