# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2

jobs:
  rubocop:
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - checkout
      - run: bundle install
      - run: rubocop .

workflows:
  version: 2
  build_and_test:
    jobs:
      - rubocop
